wandb_version: 1

epoch:
  desc: null
  value: 100
lr:
  desc: null
  value: 0.001
hidden_size:
  desc: null
  value: 60
batch_size:
  desc: null
  value: 340
experiment_number:
  desc: null
  value: 2
_wandb:
  desc: null
  value:
    python_version: 3.8.18
    cli_version: 0.16.5
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1712671555.0
    t:
      1:
      - 1
      - 5
      - 53
      - 55
      3:
      - 13
      - 16
      - 23
      4: 3.8.18
      5: 0.16.5
      8:
      - 3
      - 5
      13: windows-amd64
