wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.8.18
    cli_version: 0.16.5
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1712073747.0
    t:
      1:
      - 1
      - 5
      - 53
      - 55
      2:
      - 1
      - 5
      - 53
      - 55
      3:
      - 1
      - 2
      - 13
      - 19
      - 23
      4: 3.8.18
      5: 0.16.5
      8:
      - 3
      - 5
      13: windows-amd64
epoch:
  desc: null
  value: 100
inputs_size:
  desc: null
  value: 11
hidden_size:
  desc: null
  value: 20
batch_size:
  desc: null
  value: 170
lr:
  desc: null
  value: 0.1
